# Generated by Django 4.2.4 on 2023-08-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_alter_album_song_alter_song_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='song',
            field=models.ManyToManyField(blank=True, related_name='album_song', to='models.song'),
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ManyToManyField(blank=True, related_name='song_album', to='models.album'),
        ),
    ]
