name: Flake8 tests

on:
  push:
    branches:
      - main

jobs:
  flake8:
    runs-on: ubuntu-latest
    name: Flake8
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: flake8 Lint
        uses: py-actions/flake8@v2
